name: 03 - Build Deploy .NET App Service

on:
  push:
    paths:
      - "src/reflecta.web/**"
      - .github/workflows/03-build-deploy-app-service.yml
  workflow_dispatch:

env:
  APP_NAME: "app-reflectapoc2"
  DOTNET_VERSION: "8.x"
  NODE_VERSION: "20"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: src/reflecta.web

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        working-directory: src/reflecta.web
        run: dotnet restore

      - name: Build .NET project
        working-directory: src/reflecta.web
        run: dotnet build --configuration Release

      - name: Publish .NET project
        working-directory: src/reflecta.web
        run: dotnet publish --configuration Release --output ${{github.workspace}}/publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          package: ${{github.workspace}}/publish
