name: 05 - Temporary role assignment

on:
  workflow_dispatch:

env:
  USER_NAME: "idris.lokhandwala@microsoft.com"
  RG_NAME: "reflecta-demo-rg"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Perform role assignment
        run: |          
          az role assignment create --assignee $USER_NAME --role "Reader" --scope --scope "/subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/$RG_NAME"
