name: ACA test

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # echo a test message
      - name: Echo test message
        run: echo "Hello, world!"
