name: ACA test

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # echo a test message
      - name: Echo test message
        run: echo "Hello, world!"


      - name: Azure CLI Action
        uses: Azure/cli@v2.0.0
        with:
          # Specify the script here
          inlineScript: 
            az --version          
