on: [push]
name: IAC-Infra-Test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: github-actions-deployment-rg
          template: ./iac/iac-azuredeploy.json
          parameters: ./iac/iac-dev-parameters.json
          deploymentName: github-ilo-test

      - name: Display deployment group operation list
        run: |
          az deployment operation group list --resource-group github-actions-deployment-rg --name github-ilo-test

      - name: Display failed operations
        run: |
            az deployment operation group list --resource-group github-actions-deployment-rg --name github-ilo-test --query "[?properties.provisioningState=='Failed']"

      - name: Display status message of failed operations
        run: |
            az deployment operation group list --resource-group github-actions-deployment-rg --name github-ilo-test --query "[?properties.provisioningState=='Failed'].properties.statusMessage.error"
