name: Build and Push python generation Docker Image to ACR

on:
  workflow_dispatch:
    inputs:
      rgName:
        description: "Azure Resource Group Name"
        required: true
        default: "reflecta-demo-rg"
      acrName:
        description: "Azure Container Registry name"
        required: true
        default: "crreflectademo"
      openaiInstanceName:
        description: "OpenAI Instance Name"
        required: true
        default: "cog-reflectademo"
      storageAccountName:
        description: "Azure Storage Account Name"
        required: true
        default: "streflectademo"
      azureStorageQueueName:
        description: "Azure Storage Queue Name"
        required: true
        default: "input-validation-queue"
      azureStorageContainerName:
        description: "Azure Storage Container Name"
        required: true
        default: "embeddings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: src/reflecta.generation

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Display input parameters
        run: |
          echo "Resource Group Name: ${{ github.event.inputs.rgName }}"
          echo "ACR name: ${{ github.event.inputs.acrName }}"
          echo "OpenAI API Key: ${{ github.event.inputs.openaiInstanceName }}"
          echo "OpenAI API Base: ${{ github.event.inputs.storageAccountName }}"
          echo "Azure Storage Queue Name: ${{ github.event.inputs.azureStorageQueueName }}"
          echo "Azure Storage Container Name: ${{ github.event.inputs.azureStorageContainerName }}"
